apiVersion: rds.aws.jet.crossplane.io/v1alpha2
kind: Instance
metadata:
  name: crossplane-deep-dive-dbinstance
spec:
  forProvider:
    region: eu-west-1
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 14
    instanceClass: db.t3.micro
    engine: postgres
    engineVersion: "13.6"
    username: adminuser
    passwordSecretRef:
      key: password
      name: crossplane-deep-dive-dbinstance
      namespace: crossplane-system
    backupWindow: "09:46-10:16"
    maintenanceWindow: "Mon:00:00-Mon:03:00"
    publiclyAccessible: false
    skipFinalSnapshot: true
    storageEncrypted: false
    storageType: gp2
    parameterGroupNameRef:
      name: crossplane-deep-dive-parametergroup
  writeConnectionSecretToRef:
    name: crossplane-deep-dive-dbinstance-out
    namespace: default
