---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xpostgresqlinstances.aws.database.example.org
  labels:
    provider: aws
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: XPostgreSQLInstance
  resources:
    - name: parametergroup
      base:
        apiVersion: rds.aws.jet.crossplane.io/v1alpha2
        kind: ParameterGroup
        spec:
          forProvider:
            region: eu-central-1
            description: "RDS Composition demo group"
            family: postgres13
            parameter:
              - name: log_connections
                value: "1"
    - name: rdsinstance
      base:
        apiVersion: rds.aws.jet.crossplane.io/v1alpha2
        kind: Instance
        spec:
          forProvider:
            region: eu-central-1
            autoMinorVersionUpgrade: true
            backupRetentionPeriod: 14
            instanceClass: db.t3.micro
            engine: postgres
            engineVersion: "13.6"
            username: adminuser
            passwordSecretRef:
              key: password
              namespace: crossplane-system
            backupWindow: "09:46-10:16"
            maintenanceWindow: "Mon:00:00-Mon:03:00"
            publiclyAccessible: false
            skipFinalSnapshot: true
            storageEncrypted: false
            storageType: gp2
            parameterGroupNameSelector:
              matchControllerRef: true
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-postgresql"
        - fromFieldPath: "spec.parameters.storageGB"
          toFieldPath: "spec.forProvider.allocatedStorage"
        - fromFieldPath: "spec.parameters.passwordSecretName"
          toFieldPath: "spec.forProvider.passwordSecretRef.name"
      connectionDetails:
        - fromFieldPath: "status.atProvider.endpoint"
          name: endpoint
        - fromFieldPath: "spec.forProvider.username"
          name: username
        - fromConnectionSecretKey: "attribute.password"
          name: password
