apiVersion: azure.jet.crossplane.io/v1alpha2
kind: ResourceGroup
metadata:
  name: crossplane-deep-dive
spec:
  forProvider:
    location: "West Europe"
    tags:
      provisioner: crossplane
  providerConfigRef:
    name: default
